ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(150);
ALTER TABLE users ADD COLUMN IF NOT EXISTS cop_number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS documents TEXT[] DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id VARCHAR(255) UNIQUE;
